import type { Metadata } from 'next';
import { profile } from '@/data/profile';
import { projects } from '@/data/projects';
import { SITE_URL } from '@/lib/constants';

export const siteMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: `${profile.brandName} — ${profile.title}`,
  description: profile.positioning,
  keywords: [
    'Md Nuruzzaman',
    'Nuruzzaman',
    'Software Engineer',
    'Full-stack Developer',
    'Competitive Programmer',
    'FastAPI',
    'Next.js',
    'AWS',
    'Codeforces Expert',
  ],
  authors: [{ name: profile.name, url: SITE_URL }],
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    url: SITE_URL,
    title: `${profile.brandName} — ${profile.title}`,
    description: profile.positioning,
    siteName: profile.brandName,
    // Generated by src/app/opengraph-image.tsx (next/og) — declared explicitly for scrapers
    // that skip the file-convention discovery.
    images: [{ url: '/opengraph-image', width: 1200, height: 630, alt: `${profile.brandName} — ${profile.title}` }],
  },
  twitter: {
    card: 'summary_large_image',
    title: `${profile.brandName} — ${profile.title}`,
    description: profile.positioning,
    images: ['/opengraph-image'],
  },
};

/** JSON-LD Person + per-project CreativeWork graph — inject in layout for recruiter SEO. */
export const personJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: profile.name,
  jobTitle: profile.title,
  email: profile.email,
  url: SITE_URL,
  image: `${SITE_URL}/opengraph-image`,
  worksFor: { '@type': 'Organization', name: 'Hedaya Global Solutions' },
  sameAs: [
    profile.socials.github,
    profile.socials.linkedin,
    profile.socials.codeforces,
    profile.socials.leetcode,
    profile.socials.codechef,
    profile.socials.atcoder,
  ],
};

/** One CreativeWork per project, pointing at its indexable case-study page. */
export const projectsJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'ItemList',
  itemListElement: projects.map((p, i) => ({
    '@type': 'ListItem',
    position: i + 1,
    item: {
      '@type': 'CreativeWork',
      name: p.title,
      description: p.description,
      url: `${SITE_URL}/projects/${p.slug}`,
      author: { '@type': 'Person', name: profile.name, url: SITE_URL },
    },
  })),
};
