import type { Metadata } from 'next';
import { profile } from '@/data/profile';
import { SITE_URL } from '@/lib/constants';

export const siteMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: `${profile.brandName} — ${profile.title}`,
  description: profile.positioning,
  keywords: [
    'Md Nuruzzaman',
    'Nuruzzaman',
    'Software Engineer',
    'Full-stack Developer',
    'Competitive Programmer',
    'FastAPI',
    'Next.js',
    'AWS',
    'Codeforces Expert',
  ],
  authors: [{ name: profile.name, url: SITE_URL }],
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    url: SITE_URL,
    title: `${profile.brandName} — ${profile.title}`,
    description: profile.positioning,
    siteName: profile.brandName,
    // OG image is generated by src/app/opengraph-image.tsx (next/og).
  },
  twitter: {
    card: 'summary_large_image',
    title: `${profile.brandName} — ${profile.title}`,
    description: profile.positioning,
  },
};

/** JSON-LD Person schema — inject in layout for recruiter SEO. */
export const personJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: profile.name,
  jobTitle: profile.title,
  email: profile.email,
  url: SITE_URL,
  image: `${SITE_URL}/opengraph-image`,
  worksFor: { '@type': 'Organization', name: 'Hedaya Global Solutions' },
  sameAs: [
    profile.socials.github,
    profile.socials.linkedin,
    profile.socials.codeforces,
    profile.socials.leetcode,
    profile.socials.codechef,
    profile.socials.atcoder,
  ],
};
